development:
    api_domain: "http://3.94.101.27:8080"
    webserver_domain: "http://35.175.140.221:8080"
    
production:
    api_domain: "https://api.blogembed.com"
    webserver_domain: "https://blogembed.com"    