development:
    api_domain: "http://3.82.98.162:8080"
    webserver_domain: "http://54.152.228.71:8080"
    
production:
    api_domain: "https://api.blogembed.com"
    webserver_domain: "https://blogembed.com"    