development:
    api_domain: "http://18.212.7.108:8080"
    webserver_domain: "http://52.87.204.171:8080"
    
production:
    api_domain: "https://api.blogembed.com"
    webserver_domain: "https://blogembed.com"    